name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: Code Linting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Super-Linter
        uses: github/super-linter@v4
        env:
          VALIDATE_PYTHON_PYLINT: true
          VALIDATE_PYTHON_BLACK: false
          VALIDATE_ALL_CODEBASE: true

  unit-tests:
    name: Unit Tests with Coverage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests with coverage
        run: |
          pytest --cov=. --cov-report=xml --cov-report=html

      - name: Upload coverage report
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: htmlcov/

  todo-check:
    name: Detect TODOs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Find TODOs
        run: |
          grep -r "TODO" . > todo_report.txt
          if [ -s todo_report.txt ]; then
            echo "TODOs found, creating an issue"
          else
            echo "No TODOs found"
          fi
        shell: bash

      - name: Create GitHub Issue for TODOs
        uses: peter-evans/create-issue-from-file@v4
        with:
          title: "Found TODOs in code"
          content-filepath: todo_report.txt
